# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "trusty-x64-server"
  config.vm.box_url = "http://some-hosting-service/trusty-x64-server.box"
  config.vm.provision "shell", path: "update-apt.sh"
  config.vm.provision "shell", path: "add-host-name.sh", args: "mongo 192.168.44.10"
  config.vm.provision "shell", path: "add-host-name.sh", args: "redis 192.168.44.20"
  config.vm.provision "shell", path: "add-host-name.sh", args: "rabbitmq 192.168.44.30"
  config.vm.provision "shell", path: "add-host-name.sh", args: "ide 192.168.44.50"
  config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/Neon"]
      v.customize ["modifyvm", :id, "--memory", "256"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.customize ["modifyvm", :id, "--vram", "10"]
  end

  config.vm.define "mongodb" do |mongodb|
      mongodb.vm.hostname = "mongodb"
      mongodb.vm.provision :shell, path: "install-mongo.sh"
      mongodb.vm.network :private_network, ip: "192.168.44.10"
      mongodb.vm.provider "virtualbox" do |v|
          v.name = "a.mongodb"
      end
  end

  config.vm.define "redis" do |redis|
      redis.vm.hostname = "redis"
      redis.vm.provision :shell, path: "install-redis.sh"
      redis.vm.network :private_network, ip: "192.168.44.20"
      redis.vm.provider "virtualbox" do |v|
          v.name = "a.redis"
      end
  end

  config.vm.define "rabbitmq" do |rabbitmq|
      rabbitmq.vm.hostname = "rabbitmq"
      rabbitmq.vm.provision :shell, path: "install-rabbitmq.sh"
      rabbitmq.vm.network :private_network, ip: "192.168.44.30"
      rabbitmq.vm.provider "virtualbox" do |v|
          v.name = "a.rabbitmq"
      end
  end

  config.vm.define "ide" do |ide|
      ide.vm.box = "trusty-x64-xubuntu"
      ide.vm.box_url = "http://some-hosting-serice/trusty-x64-kubuntu.box"
      ide.vm.hostname = "ide"
      ide.vm.network :private_network, ip: "192.168.44.50"
      ide.vm.provision "shell", path: "install-vcs.sh"
      ide.vm.provision "shell", path: "install-jdk-8.sh"
      ide.vm.provision "shell", path: "install-maven.sh"
      ide.vm.provision "shell", path: "install-ant.sh"
      ide.vm.provision "shell", path: "correct-gnome-keyring.sh"
      ide.vm.provision "shell", path: "install-emacs.sh"
      ide.vm.provision "shell", path: "install-chromium.sh"
      ide.vm.provision "shell", path: "install-development-scripts.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-desktop-launchers.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-python-pip.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-pycharm.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-intellij.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-development-tomcat-7.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-gvm.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-alias-file.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-rest-shell.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-emacs-clojure-environment.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-leiningen.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-light-table.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-sts.sh", args: "vagrant"
      ide.vm.provision "shell", path: "install-ggts.sh", args: "vagrant"
      ide.vm.provider "virtualbox" do |v|
          v.name = "a.ide"
          v.gui = true
          v.customize ["modifyvm", :id, "--memory", "4096"]
          v.customize ["modifyvm", :id, "--vram", "24"]
          v.customize ["modifyvm", :id, "--cpus", "2"]
      end
  end

end
